### ISSUE TITLE
Better error message possible

### ISSUE THREAD

**Issue by offirgolan** [quaertym/ember-cli-dependency-checker#48]
A try catch [here] (https://github.com/quaertym/ember-cli-dependency-checker/blob/master/lib/package.js#L21) would allow us to include which package failed. 

The existing error message is as follows:
```bash
Invalid Version: *
TypeError: Invalid Version: *
    at new SemVer (/Users/offirgolan/Documents/Projects/Ember-Components/ember-cp-validations/node_modules/ember-cli-dependency-checker/node_modules/semver/semver.js:295:11)
    at Range.test (/Users/offirgolan/Documents/Projects/Ember-Components/ember-cp-validations/node_modules/ember-cli-dependency-checker/node_modules/semver/semver.js:1049:15)
    at Function.satisfies (/Users/offirgolan/Documents/Projects/Ember-Components/ember-cp-validations/node_modules/ember-cli-dependency-checker/node_modules/semver/semver.js:1098:16)
    at Function.VersionChecker.satisfies (/Users/offirgolan/Documents/Projects/Ember-Components/ember-cp-validations/node_modules/ember-cli-dependency-checker/lib/version-checker.js:31:17)
    at Package.updateRequired (/Users/offirgolan/Documents/Projects/Ember-Components/ember-cp-validations/node_modules/ember-cli-dependency-checker/lib/package.js:21:26)
    at Package.init (/Users/offirgolan/Documents/Projects/Ember-Components/ember-cp-validations/node_modules/ember-cli-dependency-checker/lib/package.js:15:27)
    at new Package (/Users/offirgolan/Documents/Projects/Ember-Components/ember-cp-validations/node_modules/ember-cli-dependency-checker/lib/package.js:4:13)
    at EmberCLIDependencyChecker.<anonymous> (/Users/offirgolan/Documents/Projects/Ember-Components/ember-cp-validations/node_modules/ember-cli-dependency-checker/lib/dependency-checker.js:122:12)
    at Array.map (native)
    at EmberCLIDependencyChecker.readDependencies (/Users/offirgolan/Documents/Projects/Ember-Components/ember-cp-validations/node_modules/ember-cli-dependency-checker/lib/dependency-checker.js:118:36)
```

Proposed error message:
```
Package: <Package Name> - <Reason>
Path: <Path>
# ... rest of stack trace
```

**Comment by konradjurk** [comment]
+1

**Comment by Folatt** [comment]
+ 1

**Comment by quaertym** [comment]
@offirgolan Interested in submitting a PR?
