### ISSUE TITLE
The addon `ember-cli-pagination` requires the npm package `ember-cli` to be above 1.13.0, but you have 2.2.0-beta.1.

### ISSUE THREAD

**Issue by dsaenztagarro** [quaertym/ember-cli-dependency-checker#54]
```
The addon `ember-cli-pagination` requires the npm package `ember-cli` to be above 1.13.0, but you have 2.2.0-beta.1.
Error: The addon `ember-cli-pagination` requires the npm package `ember-cli` to be above 1.13.0, but you have 2.2.0-beta.1.
    at DependencyVersionChecker.assertAbove (/Users/dsaenzt/Projects/js_image_client2/node_modules/ember-cli-pagination/node_modules/ember-cli-version-checker/index.js:81:18)
    at Class.module.exports.init (/Users/dsaenzt/Projects/js_image_client2/node_modules/ember-cli-pagination/index.js:10:37)
    at new Class (/Users/dsaenzt/Projects/js_image_client2/node_modules/ember-cli/node_modules/core-object/core-object.js:18:12)
    at /Users/dsaenzt/Projects/js_image_client2/node_modules/ember-cli/lib/models/addons-factory.js:48:19
    at visit (/Users/dsaenzt/Projects/js_image_client2/node_modules/ember-cli/lib/utilities/DAG.js:23:3)
    at DAG.topsort (/Users/dsaenzt/Projects/js_image_client2/node_modules/ember-cli/lib/utilities/DAG.js:82:7)
    at AddonsFactory.initializeAddons (/Users/dsaenzt/Projects/js_image_client2/node_modules/ember-cli/lib/models/addons-factory.js:44:9)
    at Project.initializeAddons (/Users/dsaenzt/Projects/js_image_client2/node_modules/ember-cli/lib/models/project.js:376:36)
    at Project.eachAddonCommand (/Users/dsaenzt/Projects/js_image_client2/node_modules/ember-cli/lib/models/project.js:427:10)
    at module.exports (/Users/dsaenzt/Projects/js_image_client2/node_modules/ember-cli/lib/cli/lookup-command.js:33:13)
```

**Comment by quaertym** [comment]
I think this issue belongs to ember-cli-version-checker, see https://github.com/rwjblue/ember-cli-version-checker/blob/master/index.js#L76.

**Comment by rwjblue** [comment]
Well, the issue is really with ember-cli-in pagination. The semver package does not consider prerelease to satisfy these types of ranges. The addon should use gt instead of isAbove (or I should make isAbove use gt internally).

/cc @cowboyd

**Comment by dsaenztagarro** [comment]
Guys sorry for the lost of time.. I didn't realise the error was in fact in the last line on https://github.com/mharris717/ember-cli-pagination/blob/master/index.js

I have yet reported the problem... thank you very much anyway!
