### ISSUE TITLE
Unhelpful message `TypeError: Invalid Version: *`

### ISSUE THREAD

**Issue by xdumaine** [quaertym/ember-cli-dependency-checker#75]
After having linked a local module for development, and forgetting I had done so, I was left with this unhelpful message:

```text
~/Code/project (develop *)$ ember dependency-lint
Invalid Version: *
TypeError: Invalid Version: *
    at new SemVer (/Users/pcm/Code/web-directory/node_modules/ember-cli-dependency-checker/node_modules/semver/semver.js:295:11)
    at Range.test (/Users/pcm/Code/web-directory/node_modules/ember-cli-dependency-checker/node_modules/semver/semver.js:1049:15)
    at Function.satisfies (/Users/pcm/Code/web-directory/node_modules/ember-cli-dependency-checker/node_modules/semver/semver.js:1098:16)
    at Function.VersionChecker.satisfies (/Users/pcm/Code/web-directory/node_modules/ember-cli-dependency-checker/lib/version-checker.js:31:17)
    at Package.updateRequired (/Users/pcm/Code/web-directory/node_modules/ember-cli-dependency-checker/lib/package.js:21:26)
    at Package.init (/Users/pcm/Code/web-directory/node_modules/ember-cli-dependency-checker/lib/package.js:15:27)
    at new Package (/Users/pcm/Code/web-directory/node_modules/ember-cli-dependency-checker/lib/package.js:4:13)
    at EmberCLIDependencyChecker.<anonymous> (/Users/pcm/Code/web-directory/node_modules/ember-cli-dependency-checker/lib/dependency-checker.js:133:12)
    at Array.map (native)
    at EmberCLIDependencyChecker.readDependencies (/Users/pcm/Code/web-directory/node_modules/ember-cli-dependency-checker/lib/dependency-checker.js:129:36)
```

By following that stacktrace though to [here](https://github.com/quaertym/ember-cli-dependency-checker/blob/master/lib/dependency-checker.js#L133) I just threw in this:

```javascript
    try {
        return new Package(name, versionSpecified, versionInstalled, path);
    } catch (e) {
        console.error('Error mapping package', name, versionSpecified, versionInstalled, path);
        throw(e);
    }
```

Which gave me a much more helpful

`Error mapping package SimpleWebRTC ~2.2.0 * bower_components/SimpleWebRTC`

If you'd be amenable to this change, or even just a helpful console log `if versionSpecified or versionInstalled is '*'` I'll open a PR.

**Comment by Darep** [comment]
Just ran into this as well :) I like your idea. Could a more verbose message work?

```javascript
console.error(`Error mapping package ${path} (version specified: ${versionSpecified}, installed: ${versionInstalled})`);
```

**Comment by quaertym** [comment]
👍  A PR would be great.
